ALTER TABLE profiles ADD COLUMN IF NOT EXISTS company_tagline VARCHAR(150);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS company_sector VARCHAR(50);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS company_size VARCHAR(20);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS company_cnpj VARCHAR(14);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS company_website VARCHAR(500);
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS company_founded_year INTEGER;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS company_geo_presence VARCHAR(50);
