-- ============================================================
-- SCHEMA BASELINE (GENERATED - REVIEW BEFORE TRUSTING)
-- ============================================================
--
-- These tables exist in the live database but were never captured in a
-- migration: every other migration here only ALTERs them. Without this
-- file the schema cannot be rebuilt from the repository, which means no
-- local development, no CI against a real schema, and no recovery path.
--
-- Generated by scripts/generate-schema-baseline.cjs from
-- src/types/supabase.ts. Because that file is generated from the live
-- schema, these are read from real metadata and are accurate:
--   * table names
--   * column names
--   * nullability
--   * foreign key columns and their targets
--
-- NOT captured, because the generated TypeScript types do not carry it:
--   * exact scalar types (BIGINT vs INTEGER, TEXT vs VARCHAR(n), numeric
--     precision) - these are INFERRED
--   * DEFAULT expressions
--   * CHECK constraints and enum domains
--   * ON DELETE / ON UPDATE behaviour (CASCADE is assumed everywhere)
--   * UNIQUE constraints and every index
--   * RLS policies
--   * triggers and trigger functions (including the auth.users -> profiles
--     signup trigger this schema depends on)
--
-- Reconcile against `supabase db dump --schema public` from a machine with
-- database credentials before treating this as canonical.
-- See docs/schema-baseline.md.
--
-- RLS is enabled with NO policies for every table: deny-by-default is the
-- safe failure mode for a rebuilt environment. The real policies must be
-- recovered from the live project and committed alongside this file, or
-- authenticated reads will return nothing.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.alerts (
  asset_id TEXT,
  channel TEXT,
  condition_type TEXT NOT NULL,
  created_at TIMESTAMPTZ,
  frequency TEXT,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  is_active BOOLEAN,
  last_triggered_at TIMESTAMPTZ,
  name TEXT NOT NULL,
  threshold_value NUMERIC,
  user_id UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS public.api_keys (
  created_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  is_active BOOLEAN,
  key_hash TEXT NOT NULL,
  key_prefix TEXT NOT NULL,
  last_used_at TIMESTAMPTZ,
  name TEXT NOT NULL,
  permissions JSONB,
  user_id UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS public.audit_log (
  action TEXT NOT NULL,
  created_at TIMESTAMPTZ,
  details JSONB,
  entity_id TEXT,
  entity_type TEXT,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ip_address TEXT NOT NULL,
  organization_id UUID,
  user_id UUID
);

CREATE TABLE IF NOT EXISTS public.bans (
  created_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  moderator_id UUID NOT NULL,
  reason TEXT,
  user_id UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS public.carbon_credits (
  created_at TIMESTAMPTZ,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT,
  quantity NUMERIC NOT NULL,
  retirement_account TEXT,
  retirement_beneficiary TEXT,
  retirement_beneficiary_harmonized TEXT,
  retirement_note TEXT,
  retirement_reason TEXT,
  transaction_date TIMESTAMPTZ,
  transaction_type TEXT,
  vintage INTEGER
);

CREATE TABLE IF NOT EXISTS public.carbon_projects (
  category TEXT,
  country TEXT NOT NULL,
  created_at TIMESTAMPTZ,
  first_issuance_at TIMESTAMPTZ,
  first_retirement_at TIMESTAMPTZ,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_compliance BOOLEAN,
  issued NUMERIC,
  listed_at TIMESTAMPTZ,
  name TEXT NOT NULL,
  project_id TEXT NOT NULL,
  project_type TEXT,
  project_type_source TEXT,
  project_url TEXT,
  proponent TEXT,
  protocol TEXT,
  registry TEXT,
  retired NUMERIC,
  status TEXT
);

CREATE TABLE IF NOT EXISTS public.comments (
  author_id UUID NOT NULL,
  challenge_id UUID,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  is_deleted BOOLEAN,
  karma INTEGER,
  parent_id UUID,
  post_id UUID,
  updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.karma_transactions (
  amount NUMERIC NOT NULL,
  created_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID,
  reason TEXT NOT NULL,
  user_id UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notifications (
  created_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  is_read BOOLEAN,
  message TEXT NOT NULL,
  title TEXT NOT NULL,
  type TEXT NOT NULL,
  updated_at TIMESTAMPTZ,
  user_id UUID
);

CREATE TABLE IF NOT EXISTS public.organizations (
  created_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  plan TEXT,
  slug TEXT NOT NULL,
  updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.post_deletions (
  created_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  moderator_id UUID NOT NULL,
  post_id UUID NOT NULL,
  reason TEXT
);

CREATE TABLE IF NOT EXISTS public.posts (
  author_id UUID NOT NULL,
  category TEXT NOT NULL,
  comment_count INTEGER,
  content TEXT,
  created_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  is_deleted BOOLEAN,
  is_locked BOOLEAN,
  karma INTEGER,
  keywords TEXT[],
  title TEXT NOT NULL,
  updated_at TIMESTAMPTZ,
  url TEXT
);

CREATE TABLE IF NOT EXISTS public.profiles (
  available_for_consulting BOOLEAN,
  avatar_url TEXT,
  bio TEXT,
  cargo TEXT,
  certifications TEXT[],
  company_cnpj TEXT,
  company_founded_year INTEGER,
  company_geo_presence TEXT,
  company_sector TEXT,
  company_size TEXT,
  company_tagline TEXT,
  company_website TEXT,
  created_at TIMESTAMPTZ,
  display_name TEXT,
  expertise_areas TEXT[],
  headline TEXT,
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  karma INTEGER,
  linkedin_url TEXT,
  organization TEXT,
  organization_id UUID,
  referral_code TEXT,
  referral_reward_claimed BOOLEAN,
  referred_by UUID,
  role TEXT,
  twitter_url TEXT,
  updated_at TIMESTAMPTZ,
  user_type TEXT,
  username TEXT NOT NULL,
  wallet_address TEXT,
  years_of_experience NUMERIC
);

CREATE TABLE IF NOT EXISTS public.reports (
  created_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reason TEXT NOT NULL,
  reporter_id UUID NOT NULL,
  status TEXT,
  target_id TEXT NOT NULL,
  target_type TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.saved_searches (
  created_at TIMESTAMPTZ,
  filters JSONB NOT NULL,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  user_id UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_achievements (
  achievement_id TEXT NOT NULL,
  earned_at TIMESTAMPTZ NOT NULL,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  metadata JSONB,
  user_id UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS public.votes (
  created_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  target_id TEXT NOT NULL,
  target_type TEXT NOT NULL,
  user_id UUID NOT NULL,
  vote_type NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS public.warnings (
  created_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  moderator_id UUID NOT NULL,
  reason TEXT NOT NULL,
  user_id UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS public.watchlist_items (
  asset_id TEXT NOT NULL,
  created_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  watchlist_id UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS public.watchlists (
  created_at TIMESTAMPTZ,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  user_id UUID NOT NULL
);


-- ------------------------------------------------------------
-- Deny-by-default RLS. Real policies must be recovered from the
-- live project and committed alongside this file.
-- ------------------------------------------------------------

ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carbon_credits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carbon_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.karma_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_deletions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_searches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warnings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watchlist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watchlists ENABLE ROW LEVEL SECURITY;
