INSERT INTO cad_trust_projects (
  org_uid,
  project_registry_name,
  project_id,
  project_name,
  project_description,
  project_link,
  project_sector,
  project_type,
  project_status,
  category,
  project_type_source,
  proponent,
  protocol,
  is_compliance,
  issued,
  retired,
  first_issuance_at,
  first_retirement_at,
  listed_at
)
SELECT
  COALESCE(registry, 'unknown'),
  COALESCE(registry, 'unknown'),
  project_id,
  name,
  NULL,
  project_url,
  category,
  project_type,
  COALESCE(status, 'Listed'),
  category,
  project_type_source,
  proponent,
  protocol,
  COALESCE(is_compliance, FALSE),
  COALESCE(issued, 0),
  COALESCE(retired, 0),
  first_issuance_at,
  first_retirement_at,
  listed_at
FROM carbon_projects;
